In [1]:
import numpy as np

In [2]:
print np.__version__

1.11.3


In [4]:
import numpy as np

In [7]:
print np.__version__

1.11.3


In [8]:
arr1 = np.array([1,4,5,6])

In [9]:
print arr1

[1 4 5 6]


In [13]:
print np.zeros(5)

[ 0.  0.  0.  0.  0.]


In [14]:
print np.ones((3,4,5))

[[[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]]


In [18]:
a = np.random.rand(100)
# print np.random.randn(6)

AttributeError: 'numpy.ndarray' object has no attribute 'avg'

In [19]:
np.random.seed(0) # 랜덤한 값을 계속 유지하고 싶을 때 사용
print np.random.rand()

np.random.seed(1)
print np.random.rand()

0.548813503927
0.417022004703


In [29]:
arr = np.random.randint(0, 100, 100)
print arr

[82 15 64 68 25 98 87  7 26 25 22  9 67 23 27 37 57 83 38  8 32 34 10 23 15
 87 25 71 92 74 62 46 32 88 23 55 65 77  3  0 77  6 52 85 70  2 76 91 21 75
  7 77 72 75 76 43 20 30 36  7 45 68 57 82 96 13 10 23 81  7 24 74 92 20 32
 12 65 94 60 24 82 97  2 92 98 10 54 96 82 86 70 66 71 48 54 15  5 17 42 20]


In [31]:
print arr[arr % 2 == 0]

[82 64 68 98 26 22 38  8 32 34 10 92 74 62 46 32 88  0  6 52 70  2 76 72 76
 20 30 36 68 82 96 10 24 74 92 20 32 12 94 60 24 82  2 92 98 10 54 96 82 86
 70 66 48 54 42 20]


In [33]:
arr = np.arange(1,10)*5
print arr

[ 5 10 15 20 25 30 35 40 45]


In [34]:
arr2 = arr**2
print arr2

[  25  100  225  400  625  900 1225 1600 2025]


In [35]:
print arr2**0.5

[  5.  10.  15.  20.  25.  30.  35.  40.  45.]


In [40]:
arr = np.random.rand(2)
print arr



[ 0.20856831  0.04930424]


In [60]:
arr1 = np.array([[1,4,5],[5,1,4]])
arr2 = np.array([[2,3],[3,7],[3,3]])
arr = np.array([])

for k in arr:
    sum = 0
    for i in arr1:
        for j in arr2:
            sum += arr1[i][j]*arr2[j][i]
            arr[k][i] = sum
        

[[1 4 5]
 [5 1 4]]
[[1 4 5]
 [5 1 4]]
[[1 4 5]
 [5 1 4]]
[[1 4 5]
 [5 1 4]]


In [49]:
len(arr1)

2

In [73]:
import pandas as pd