In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [6]:
arr1 = np.array([1, 3, 5, 6])
arr2 = np.array([[2,5],[5,6]])

In [7]:
print arr1

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-7-97968826bf6a>, line 1)

In [8]:
print arr2

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-8-f60df628a811>, line 1)

In [9]:
print (arr1)

[1 3 5 6]


In [10]:
print (arr2)

[[2 5]
 [5 6]]


In [12]:
arr3 = np.arange(1,11)
print (arr3)

[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
arr4 = np.linspace(0, 100, 19)

In [20]:
print (arr4)

[   0.            5.55555556   11.11111111   16.66666667   22.22222222
   27.77777778   33.33333333   38.88888889   44.44444444   50.
   55.55555556   61.11111111   66.66666667   72.22222222   77.77777778
   83.33333333   88.88888889   94.44444444  100.        ]


In [32]:
arr5 = np.zeros((10,3))

In [33]:
print (arr5)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [35]:
arr = np.random.rand(5)

In [36]:
print (arr)

[ 0.83439876  0.17254504  0.07160586  0.74397886  0.81273987]


In [37]:
arr = np.random.randn(10)

In [38]:
print(arr)

[-0.3858974   1.63966641 -0.00727372  0.56017021 -0.49097835 -0.5398537
 -0.44839043 -0.20233465  0.17959045  1.5707951 ]


In [41]:
arr = np.random.seed(0)

In [42]:
print (arr)

None


In [4]:
import numpy as np
import pandas as pd
arr1 = np.array([1, 3, 4, 6])
arr2 = np.array([[0, 1, 3], [2, 4, 6]])

In [6]:
print arr1[1:3]

[3 4]


In [7]:
print arr2[0]

[0 1 3]


In [8]:
print arr2[0,1]

1


In [9]:
print arr2[1:,:2]

[[2 4]]


In [11]:
print arr2[:,:2]

[[0 1]
 [2 4]]


In [12]:
arr = np.random.randint(0,10,10)
print arr

[7 9 7 3 7 3 8 4 2 2]


In [13]:
arr = np.arange(1,8) **2
print arr

[ 1  4  9 16 25 36 49]


In [15]:
arr1 = np.arange(0,30,2)
print arr1

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [ ]:
arr = np.random()

In [2]:
import numpy as np
import pandas as pd

In [3]:
arr = np.arange(0,100, 3) # 0부터 100까지를 3step으로

In [4]:
print (arr)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [5]:
arr = np.arange(100)
print (arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [22]:
arr = np.random.randint(0,30,30) # 0부터 30까지 랜덤하게 정수반환 =>

In [23]:
print (arr)

[21  2 27 14 24  2 24 17 24  8 12 24 17  2 12 21 26 12  1 10 21 17 26 13 22
  6 10 12 15 19]


In [27]:
arr = np.arange(0,30,3)
arr2 = np.arange(1,11)

print (arr, arr2)
print (arr - arr2)
print (arr * arr2)

[ 0  3  6  9 12 15 18 21 24 27] [ 1  2  3  4  5  6  7  8  9 10]
[-1  1  3  5  7  9 11 13 15 17]
[  0   6  18  36  60  90 126 168 216 270]


In [28]:
arr = np.random.randint(1,100,size =(5,5))

In [29]:
print (arr)

[[10 28 59 13 20]
 [ 4  2 20 17 71]
 [26 75 77 77 93]
 [ 5 76 31 27 18]
 [38 21 18 33 22]]


In [30]:
print np.all(arr>50?)

SyntaxError: invalid syntax (<ipython-input-30-6511acf45810>, line 1)

In [31]:
print np.all(arr<50)

SyntaxError: invalid syntax (<ipython-input-31-15edd22ceee5>, line 1)

In [32]:
import numpy as np

In [33]:
print np.all(arr>50)

SyntaxError: invalid syntax (<ipython-input-33-5349108dd9e8>, line 1)

In [34]:
print np.any(arr > 4-)

SyntaxError: invalid syntax (<ipython-input-34-bed45c87eb04>, line 1)

In [1]:
import numpy as np
import pandas as pd

In [2]:
arr = np.array([np.arange(1,6), np.arange(10,15)])

In [3]:
print (arr)

[[ 1  2  3  4  5]
 [10 11 12 13 14]]


In [4]:
print arr.ravel()

SyntaxError: invalid syntax (<ipython-input-4-86d715a92f0c>, line 1)

In [1]:
import numpy as np
import pandas as pd

In [2]:
arr = np.random.randint(1,10, size= (5,5))

In [3]:
print arr

[[5 6 4 9 8]
 [7 2 6 6 7]
 [1 3 3 5 8]
 [8 4 6 8 9]
 [8 8 8 5 9]]


In [4]:
print np.all(arr>10)

False


In [5]:
arr = np.array([np.arange(1,6), np.arange(10,15)])

In [6]:
print arr

[[ 1  2  3  4  5]
 [10 11 12 13 14]]


In [7]:
print arr.ravel()

[ 1  2  3  4  5 10 11 12 13 14]


In [8]:
arr = np.arange(1,16)
print arr

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [9]:
print arr.reshape(3,5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [10]:
s1 = pd.Series(20)

In [11]:
print s1

0    20
dtype: int64


In [13]:
s2 = pd.Series(range(1,6))

In [14]:
print s2

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [15]:
print s2.values

[1 2 3 4 5]


In [16]:
print s2.index

RangeIndex(start=0, stop=5, step=1)


In [18]:
s3 = pd.Series(range(1,4), index = ['a','b','c'])
print s3

a    1
b    2
c    3
dtype: int64


In [19]:
s3.values

array([1, 2, 3], dtype=int64)

In [20]:
s3.index

Index([u'a', u'b', u'c'], dtype='object')

In [21]:
print s3[1]

2


In [22]:
print s3['c']

3


In [23]:
s4 = pd.Series(2, index = s3.index)
print s4

a    2
b    2
c    2
dtype: int64


In [24]:
s5 = pd.Series(np.random.randn(5))

In [25]:
print s5

0    1.657904
1    2.056573
2    0.768762
3   -0.256667
4   -1.683024
dtype: float64


In [26]:
s6 = pd.Series(np.arange(1,11))

In [27]:
print s6

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int32


In [28]:
s7 = pd.Series({'a':1000, 'b':50, 'c': 19, 'd':20})

In [29]:
print s7

a    1000
b      50
c      19
d      20
dtype: int64


In [37]:
s = pd.Series([1,2,3,4,5,6,7,7,7,7,np.nan]) 

In [38]:
print s

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     7.0
8     7.0
9     7.0
10    NaN
dtype: float64


In [39]:
print len(s)

11


In [40]:
print s.size

11


In [41]:
print s.shape

(11,)


In [42]:
print s.count()

10


In [43]:
print s.unique()

[  1.   2.   3.   4.   5.   6.   7.  nan]


In [44]:
print s.value_counts()

7.0    4
6.0    1
5.0    1
4.0    1
3.0    1
2.0    1
1.0    1
dtype: int64


In [45]:
s.head()

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [46]:
s.head(3)

0    1.0
1    2.0
2    3.0
dtype: float64

In [47]:
s.tail()

6     7.0
7     7.0
8     7.0
9     7.0
10    NaN
dtype: float64

In [48]:
s = pd.Series(np.arange(1,5), index = ['x','y','z','k'])

In [49]:
s.take([0,2])

x    1
z    3
dtype: int32

In [50]:
print s['x']

1


In [51]:
print s[1]

2


In [52]:
print s[['x','z']]

x    1
z    3
dtype: int32


In [53]:
s = pd.Series([1,2,3], index=[100,101,102])

In [54]:
print s

100    1
101    2
102    3
dtype: int64


In [55]:
print s.loc[100]

1


In [56]:
print s.iloc[0]

1


In [57]:
print s.loc[[100,102]]

100    1
102    3
dtype: int64


In [58]:
print s.iloc[[0,2]]

100    1
102    3
dtype: int64


In [59]:
s.loc[[100, 102, 104, 109]]

100    1.0
102    3.0
104    NaN
109    NaN
dtype: float64

In [61]:
s = pd.Series(np.arange(1,10))

In [62]:
s > 5

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [67]:
s1 = s[s>5]

In [72]:
s1.values

array([6, 7, 8, 9])

In [74]:
df = pd.DataFrame(np.array([[10,20],[40,100]]))

In [75]:
print df

    0    1
0  10   20
1  40  100


In [77]:
df = pd.DataFrame([pd.Series(np.arange(10,15)),pd.Series(np.arange(20,22))])

In [78]:
print df

      0     1     2     3     4
0  10.0  11.0  12.0  13.0  14.0
1  20.0  21.0   NaN   NaN   NaN


In [79]:
print df.shape

(2, 5)


In [80]:
print df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
0    2 non-null float64
1    2 non-null float64
2    1 non-null float64
3    1 non-null float64
4    1 non-null float64
dtypes: float64(5)
memory usage: 116.0 bytes
None


In [81]:
print df.describe()

               0          1     2     3     4
count   2.000000   2.000000   1.0   1.0   1.0
mean   15.000000  16.000000  12.0  13.0  14.0
std     7.071068   7.071068   NaN   NaN   NaN
min    10.000000  11.000000  12.0  13.0  14.0
25%    12.500000  13.500000  12.0  13.0  14.0
50%    15.000000  16.000000  12.0  13.0  14.0
75%    17.500000  18.500000  12.0  13.0  14.0
max    20.000000  21.000000  12.0  13.0  14.0


In [82]:
df = pd.DataFrame(np.array([[10,20],[30,40]]), columns =['a','b'])

In [83]:
print df

    a   b
0  10  20
1  30  40


In [91]:
s1 = pd.Series(np.arange(1,6))
s2 = pd.Series(np.arange(8,13))

In [94]:
#print s1
#print s2

df = pd.DataFrame({'c':s1,'d':s2})
print df

   c   d
0  1   8
1  2   9
2  3  10
3  4  11
4  5  12


In [99]:
sample_df = pd.read_csv('sample.csv')

In [100]:
sample_df.head()

id    city  population  area
0   1  pangyo        1000   230
1   2   seoul        2000   400
2   3   busan        5000   500
3   4    jeju         200   200

In [102]:
sample_df[['population']].mean()

population    2050.0
dtype: float64

In [103]:
print len(sample_df)

4


In [104]:
print sample_df.index

RangeIndex(start=0, stop=4, step=1)


In [106]:
print sample_df.columns

Index([u'id', u'city', u'population', u'area'], dtype='object')


In [108]:
apple_df = pd.read.csv('apple.excel')

AttributeError: 'module' object has no attribute 'read'