## 학습목표
 1. numpy & pandas basic

* numpy 
  - 기본 array 생성

In [2]:
import numpy as np     # =====> 수치해석 라이브러리
                       # pandas =====> 엑셀, numpy를 base로 한다.
    
# pip install -U numpy =====> cmd에서 typing하면 업데이트 된다.
# pip install --help =====> pip install에 대한 옵션 확인 가능

* ndarray
 - numpy의 기본 타입
 - vector, matrix를 표현
 - numpy.array([])로 생성

In [3]:
arr1 = np.array([1, 3, 4, 6])
arr2 = np.array([[0, 1, 2], [2, 4, 6]])

print arr1, type(arr1)
print arr2, type(arr2)

[1 3 4 6] <type 'numpy.ndarray'>
[[0 1 2]
 [2 4 6]] <type 'numpy.ndarray'>


* arange 
 - range()와 동일한 기능을 수행함
 - ndarray 반환

In [7]:
arr3 = np.arange(1, 11)
print arr3, type(arr3)

[ 1  2  3  4  5  6  7  8  9 10] <type 'numpy.ndarray'>


* linspace()
 - start, end를 n-1개의 균일한 간격으로 분할
 - 그래프 그릴 때 주로 사용 (간격설정)

In [8]:
# 0 - 2의 범위를 5-1 등분 한다는 이야기
arr4 = np.linspace(0, 2, 5)
print arr4

[ 0.   0.5  1.   1.5  2. ]


* zeros
 - 전달된 tuple 사이즈 행렬 반환
 - 0으로 채워짐

In [15]:
print np.zeros((2, 4))
print np.zeros(4)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[ 0.  0.  0.  0.]


* ones
 - 전달된 tuple 사이즈 행렬 반환
 - 1로 채워짐

In [14]:
print np.ones((3, 3, 2))
print np.ones(3)

[[[ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]]

 [[ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]]

 [[ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]]]
[ 1.  1.  1.]


In [224]:
print np.random.rand(3) # [0, 1] 사이 출력
print np.random.randn(3) # 정규분포

[ 0.17471078  0.39087952  0.62444133]
[-0.77486208 -0.6746441  -1.23666522]


* slicing
 - 리스트, 문자열 slicing과 동일함

In [49]:
arr1 = np.array([1, 3, 4, 6])
arr2 = np.array([[0, 1, 3], [2, 4, 6]])

In [3]:
np.random.seed(0) # 랜덤한 값을 계속 유지하고 싶을 때 사용
print np.random.rand()

np.random.seed(1)
print np.random.rand()

NameError: name 'np' is not defined

In [225]:
print arr1[0]
print arr1[1:-1] # 범위(슬라이싱)로 할 경우 차원을 유지

1
[3 4]


In [228]:
arr2 = np.array([[0, 1, 3], [2, 4, 6]])

print arr2[0]
print arr2[0, 1]
print arr2[1:, :2] # 범위(슬라이싱)로 할 경우 차원을 유지 / 행렬 -> 벡터로 변경되지 않는다.
print arr2[:, 2] # 슬라이싱이 하나면 벡터로 변경

print arr2[:, 1:]


[0 1 3]
1
[[2 4]]
[3 6]
[[1 3]
 [4 6]]


* array masking
  - numpy의 원소를 선택하거나 제거하여 추출하는 방법

In [229]:
arr = np.random.randint(0, 35, 10)
print arr

[23 12  9 33  8 16 25 31 34 31]


In [231]:
even_mask = (arr % 2 == 0)
print even_mask  # boolin형식으로 반환
print arr[even_mask] # 어떻게 보면 문법이다.


print arr[arr % 2 == 0] # 위와 동일

[False  True False False  True  True False False  True False]
[12  8 16 34]
[12  8 16 34]


* operations
  - 기본 연산은 벡터화되어 전체 원소에 적용된다.

In [232]:
arr = np.arange(1, 7) * 5
print arr

[ 5 10 15 20 25 30]


In [233]:
arr2 = arr ** 4
print arr2
print arr2 ** 0.5

[   625  10000  50625 160000 390625 810000]
[  25.  100.  225.  400.  625.  900.]


In [235]:
arr1 = np.arange(0, 30, 3) + 3
arr2 = np.arange(1, 11)
print arr1, arr2

print arr1 - arr2
print arr1 * arr2

[ 3  6  9 12 15 18 21 24 27 30] [ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[  3  12  27  48  75 108 147 192 243 300]


In [83]:
arr1 = np.array([[1, 1], [1, 1]])
arr2 = np.array([[2, 2], [2, 2]])

print arr1 * arr2  # 원소끼리의 곱
print arr1.dot(arr2) # 행렬 곱

[[2 2]
 [2 2]]
[[4 4]
 [4 4]]


* logical operator 
  - all(), any()

In [236]:
arr = np.random.randint(1, 10, size = (4,4))
print arr

[[4 3 6 2]
 [4 4 7 2]
 [8 4 1 4]
 [8 4 5 5]]


In [237]:
print np.all(arr < 11) # 전부 만족하나요?

True


In [238]:
print np.any(arr % 7 == 0) # 한개라도 있나요?

True


* ravel
  - 다차원배열을 1차원으로 늘이기

In [239]:
arr = np.array([np.arange(1, 6), np.arange(10, 15)])
print arr
print arr.ravel()

[[ 1  2  3  4  5]
 [10 11 12 13 14]]
[ 1  2  3  4  5 10 11 12 13 14]


* reshaping
 - array의 shape을 재정렬

In [240]:
arr = np.arange(1, 16)
print arr
arr2 = arr.reshape(3, 5)
print arr2
print arr

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


* 자주 쓰는 numpy 함수

In [110]:
print np.min(arr)
print np.mean(arr)
print np.median(arr)
print np.max(arr)
print np.std(arr)
print np.argmin(arr) # 최소값의 인덱스
print np.argmax(arr)
print np.sum(arr)
print np.sqrt(arr)


A =  [[2, 3, 4], [1, 2, 3]]
B =  [[2, 3], [1, 2], [3, 4]]

1
15
4.32049379894
0
14
120
[ 1.          1.41421356  1.73205081  2.          2.23606798  2.44948974
  2.64575131  2.82842712  3.          3.16227766  3.31662479  3.46410162
  3.60555128  3.74165739  3.87298335]


* 연습문제)
1. numpy를 이용하여 Math.pi 값을 다시 구해봅시다.
2. python 기본 리스트 객체로 만든 두 행렬을 곱하는 코드를 작성하시오.

3.13564


[[4, 6, 4, 4], [6, 8, 5, 5]]


* pandas basic
  - http://pandas.pydata.org/
  - Opensource python 고성능 데이터 분석 라이브러리
  - DataFrame, Series 객체가 가장 많이 사용
  - ML library인 scikit-learn과 함께 ML 분석에 많이 사용 됨
  - pip install pandas로 설치

In [245]:
import numpy as np
import pandas as pd

 * Series
  - pandas의 기본 객체 중 하나
  - numpy의 ndarray를 기반으로 인덱싱을 기능을 추가하여 1차원 배열을 나타냄
  - index를 지정하지 않을 시, 기본적으로 ndarray와 같이 0-based 인덱스 생성
  - 같은 타입의 0개 이상의 데이터를 가질 수 있음

In [246]:
s1 = pd.Series(20)
print s1

0    20
dtype: int64


In [58]:
print s1[0]

20


In [247]:
s2 = pd.Series(range(1, 6))
print s2

0    1
1    2
2    3
3    4
4    5
dtype: int64


 * 값 및 인덱스 접근
  - 각가 values, index 속성

In [248]:
print s2.values

[1 2 3 4 5]


In [249]:
print s2.index

RangeIndex(start=0, stop=5, step=1)


* index 지정하기

In [250]:
s3 = pd.Series(range(1, 4), index = ['a', 'b', 'c']) # 순서가 있는 dict개념?
print s3
print
print s3.values
print
print s3.index # 인덱스를 지정해도 0,1,2는 살아있다.

a    1
b    2
c    3
dtype: int64

[1 2 3]

Index([u'a', u'b', u'c'], dtype='object')


In [251]:
print s3[1] # 기본 인덱스
print s3['c'] 

2
3


* index 재사용

In [252]:
s4 = pd.Series(2, index = s3.index)
print s4

a    2
b    2
c    2
dtype: int64


In [253]:
s5 = pd.Series(np.random.randn(5))
print s5

0    0.817524
1   -1.511287
2    0.411231
3    0.403211
4   -0.716568
dtype: float64


In [254]:
s6 = pd.Series(np.arange(1, 9))
print s6

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64


In [255]:
s7 = pd.Series({'a' : 100, 'b' : 1000, 'c' : 2, 'd' : 6})
print s7
print s7['b']
# 딕트로도 생성가능 : 순서보장 x

a     100
b    1000
c       2
d       6
dtype: int64
1000


* Series size, shape, unique, count

In [268]:
s = pd.Series([0, 1, 1, 2, 3, 4, 5, 6, 7, np.nan])
print s
# nan : not a number

0    0.0
1    1.0
2    1.0
3    2.0
4    3.0
5    4.0
6    5.0
7    6.0
8    7.0
9    NaN
dtype: float64


In [257]:
print len(s) #s.size와 동일한가?

10


In [258]:
print s.size

10


In [89]:
print s.shape # 튜플로 모양 반환

(10,)


In [259]:
print s.count() # NaN을 제외한 값을 카운팅

9


In [260]:
print s.unique() # 중복된 숫자를 제거한 value

[  0.   1.   2.   3.   4.   5.   6.   7.  nan]


In [95]:
print s.value_counts() # NaN 제외하고 값들을 카운팅 함 / 제일 많이 쓴다.
# 시리즈로 반환

1.0    2
7.0    1
6.0    1
5.0    1
4.0    1
3.0    1
2.0    1
0.0    1
dtype: int64


* head, tail, take

In [269]:
s.head() # 상위 5개 출력

0    0.0
1    1.0
2    1.0
3    2.0
4    3.0
dtype: float64

In [270]:
s.head(n = 3)

0    0.0
1    1.0
2    1.0
dtype: float64

In [271]:
s.tail()

5    4.0
6    5.0
7    6.0
8    7.0
9    NaN
dtype: float64

In [100]:
s.tail(n = 2)

8    7.0
9    NaN
dtype: float64

In [265]:
print s
print 
print s.take([0, 4, 3, 9])

0    0.0
1    1.0
2    1.0
3    2.0
4    3.0
5    4.0
6    5.0
7    6.0
8    7.0
9    NaN
dtype: float64

0    0.0
4    3.0
3    2.0
9    NaN
dtype: float64


In [272]:
s = pd.Series(np.arange(1, 4), index = ['x', 'y', 'z'])
s.take([0, 2])
# s.take(['x', 'z']) #0 - based index만 가능
# 인덱스를 따로 지정해도 0-based index는 살아있음.

x    1
z    3
dtype: int64

* 값 접근하기

 * single value

In [1]:
print s['x']

NameError: name 's' is not defined

In [2]:
print s[1]

NameError: name 's' is not defined

* multiple values

In [114]:
print s[['x', 'z']]  # [[ ]] 대괄호 2개 사용

x    1
z    3
dtype: int64


In [275]:
s = pd.Series([1, 2, 3], index = [100, 101, 102])
print s

100    1
101    2
102    3
dtype: int64


* loc , iloc => 프레임에서 많이 사용
  - loc[] : index
  - iloc[] : 0 based index

In [120]:
print s.loc[100]

1


In [123]:
print s.iloc[0]

1


In [124]:
print s.loc[[100, 102]] 

100    1
102    3
dtype: int64


In [125]:
print s.iloc[[0, 2]]

100    1
102    3
dtype: int64


In [276]:
s.loc[[100, 102, 104, 105]]

100    1.0
102    3.0
104    NaN
105    NaN
dtype: float64

In [277]:
s.iloc[[0, 2, 1, 4, 5]] # 0-based 에서는 NaN값 반환 안되고 에러

IndexError: positional indexers are out-of-bounds

* index를 기준으로 더하기

In [278]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
print s1

a    1
b    2
c    3
d    4
dtype: int64


In [279]:
s2 = pd.Series([4, 3, 2, 1], index=['d', 'c', 'b', 'a'])
s2

d    4
c    3
b    2
a    1
dtype: int64

In [131]:
print s1 + s2

a    2
b    4
c    6
d    8
dtype: int64


In [132]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([4, 3, 2, 1])
a1 + a2

array([5, 5, 5, 5])

* 산술연산

In [136]:
print s1 ** 2
print s1

a     1
b     4
c     9
d    16
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64


In [281]:
exp = pd.Series(2, s1.index)
print s1 ** exp

a     1
b     4
c     9
d    16
dtype: int64


In [282]:
s1 = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 5})
s2 = pd.Series({'b': 6, 'c': 7, 'd': 9, 'e': 10})

print s1 + s2

a     NaN
b     8.0
c    10.0
d    14.0
e     NaN
dtype: float64


 * NaN
  - numpy와 비교

In [283]:
nda = np.array([1, 2, 3, 4, 5])
nda.mean()

3.0

In [284]:
nda = np.array([1, 2, 3, 4, np.NaN])
nda.mean()

nan

In [144]:
s = pd.Series([1, 2, 3, 4, np.NaN])
print s.mean()
print s.mean(skipna=False)

2.5
nan


 * **Boolean selection**           =====> array의 masking
  - boolean Series가 []와 함께 사용되면 True 값에 해당하는 값만 새로 반환되는 Series객체에 포함됨

In [285]:
s = pd.Series(np.arange(1, 10))
s > 5

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [286]:
my_logic = s > 5
print s[my_logic]

5    6
6    7
7    8
8    9
dtype: int64


In [147]:
print s[s > 5]


5    6
6    7
7    8
8    9
dtype: int64


In [287]:
#print s > 5 and s < 8
#print s[s > 5 and s < 8]
print s[(s > 5) & (s < 8)] # & and , | or

5    6
6    7
dtype: int64


In [5]:
print (s >= 0).all()
print (s >= 2).all()

NameError: name 's' is not defined

In [289]:
print (s < 2).any()
print s[s < 2].any()

True
True


In [170]:
print s
print 
print s[s >= 7].sum()
print (s >= 7).sum() # 불린Type : True가 3개기 때문에 3이 나옴

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

24
3


* Series 값 변경


In [290]:
s = pd.Series([1, 10, 100], index = ['a', 'b', 'c'])
s['d'] = 1000

print s

s['d'] = 10000
print s

a       1
b      10
c     100
d    1000
dtype: int64
a        1
b       10
c      100
d    10000
dtype: int64


In [291]:
del s['a']
print s

b       10
c      100
d    10000
dtype: int64


* Slicing

In [182]:
s = pd.Series(np.arange(100, 110), index=np.arange(10, 20))
print s[0:5]
print s[:5]
print s[5:]
print s[-3:]
# 슬라이싱은 무조건 zero base이다 / 내가 정한 index와 상관없이

10    100
11    101
12    102
13    103
14    104
dtype: int64
10    100
11    101
12    102
13    103
14    104
dtype: int64
15    105
16    106
17    107
18    108
19    109
dtype: int64
17    107
18    108
19    109
dtype: int64


* DataFrame
  - Series가 1차원이라면 DataFrame은 2차원으로 확대된 버젼
  - Excel spreadsheet이라고 생각하면 이해하기 쉬움
  - 2차원이기 때문에 인덱스가 row, column로 구성됨

In [292]:
import numpy as np
import pandas as pd

In [293]:
df = pd.DataFrame(np.array([[10, 11], [20, 22]]))
print df

    0   1
0  10  11
1  20  22


* shape

In [294]:
df1 = pd.DataFrame([pd.Series(np.arange(10, 15)) ,
            pd.Series(np.arange(20, 25))])
print df1
print df1.shape
print df1.info()
print df1.describe()

    0   1   2   3   4
0  10  11  12  13  14
1  20  21  22  23  24
(2, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
0    2 non-null int64
1    2 non-null int64
2    2 non-null int64
3    2 non-null int64
4    2 non-null int64
dtypes: int64(5)
memory usage: 152.0 bytes
None
               0          1          2          3          4
count   2.000000   2.000000   2.000000   2.000000   2.000000
mean   15.000000  16.000000  17.000000  18.000000  19.000000
std     7.071068   7.071068   7.071068   7.071068   7.071068
min    10.000000  11.000000  12.000000  13.000000  14.000000
25%    12.500000  13.500000  14.500000  15.500000  16.500000
50%    15.000000  16.000000  17.000000  18.000000  19.000000
75%    17.500000  18.500000  19.500000  20.500000  21.500000
max    20.000000  21.000000  22.000000  23.000000  24.000000


In [295]:
df = pd.DataFrame(np.array([[10, 20], [20, 30]]), columns = ['a', 'b'])
print df
print df.columns
print df.columns[0], df.columns[1]

df.columns = ['t1', 't2']
print df

    a   b
0  10  20
1  20  30
Index([u'a', u'b'], dtype='object')
a b
   t1  t2
0  10  20
1  20  30


In [296]:
df = pd.DataFrame(np.array([[10, 20], [20, 30]]), columns = ['a', 'b'], index = ['d1', 'd2'])
print df
print df.index
# row로 줘도 되지만 기본적으로 index라고 표현함

     a   b
d1  10  20
d2  20  30
Index([u'd1', u'd2'], dtype='object')


* Series dictionary로 부터 생성

In [297]:
s1 = pd.Series(np.arange(1, 6, 1))
s2 = pd.Series(np.arange(6, 11, 1))
df = pd.DataFrame({'c1': s1, 'c2': s2})

print df
# 시리즈 방향은 위에서 아래이다.

   c1  c2
0   1   6
1   2   7
2   3   8
3   4   9
4   5  10


In [299]:
sample_df = pd.read_csv('sample.csv', index_col = 'Symbol', usecols = [0, 1, 2, 3, 7])
print sample_df.head()
print
print sample_df[['Price']].mean() # 왜 중가로를 2번썼지?

                       Name                  Sector   Price  Book Value
Symbol                                                                 
MMM              3M Company             Industrials  177.12       19.34
ABT     Abbott Laboratories             Health Care   41.89       14.10
ABBV                 AbbVie             Health Care   64.16        2.87
ACN           Accenture plc  Information Technology  115.11       11.45
ATVI    Activision Blizzard  Information Technology   41.29       11.31

Price    86.044306
dtype: float64


In [300]:
print len(sample_df) # index의 수를 반환?

504


In [301]:
print sample_df.index
print 
print sample_df.columns

Index([u'MMM', u'ABT', u'ABBV', u'ACN', u'ATVI', u'AYI', u'ADBE', u'AAP',
       u'AES', u'AET',
       ...
       u'XEL', u'XRX', u'XLNX', u'XL', u'XYL', u'YHOO', u'YUM', u'ZBH',
       u'ZION', u'ZTS'],
      dtype='object', name=u'Symbol', length=504)

Index([u'Name', u'Sector', u'Price', u'Book Value'], dtype='object')


In [306]:
#apple_df = pd.read_csv('apple.csv', header = None)
apple_df = pd.read_csv('apple.csv')
print apple_df[:10] 
#슬라이싱만 row를 가져오고 나머진 column으로 인식 // 진행 [10]은 안됨

        Date    Open    High     Low   Close    Volume
0  30-Sep-16  112.46  113.37  111.80  113.05  36379106
1  29-Sep-16  113.16  113.80  111.80  112.18  35886990
2  28-Sep-16  113.69  114.64  113.43  113.95  29641085
3  27-Sep-16  113.00  113.18  112.34  113.09  24607412
4  26-Sep-16  111.64  113.39  111.55  112.88  29869442
5  23-Sep-16  114.42  114.79  111.55  112.71  52481151
6  22-Sep-16  114.35  114.94  114.00  114.62  31073984
7  21-Sep-16  113.85  113.99  112.44  113.55  36003185
8  20-Sep-16  113.05  114.12  112.51  113.57  34514269
9  19-Sep-16  115.19  116.18  113.25  113.58  47023046


* column 선택하기

In [307]:
print apple_df[[0, 4, 5]] # column만 가져옴 ==> 않에 값이나 리스트가 올 경우

         Date   Close     Volume
0   30-Sep-16  113.05   36379106
1   29-Sep-16  112.18   35886990
2   28-Sep-16  113.95   29641085
3   27-Sep-16  113.09   24607412
4   26-Sep-16  112.88   29869442
5   23-Sep-16  112.71   52481151
6   22-Sep-16  114.62   31073984
7   21-Sep-16  113.55   36003185
8   20-Sep-16  113.57   34514269
9   19-Sep-16  113.58   47023046
10  16-Sep-16  114.92   79886911
11  15-Sep-16  115.57   90613177
12  14-Sep-16  111.77  112340318
13  13-Sep-16  107.95   62176190
14  12-Sep-16  105.44   45292770
15   9-Sep-16  103.13   46556984
16   8-Sep-16  105.52   53002026
17   7-Sep-16  108.36   42364328
18   6-Sep-16  107.70   26880391
19   2-Sep-16  107.73   26334858
20   1-Sep-16  106.73   26701523


In [308]:
print type(apple_df[[0, 4, 5]])
print type(apple_df[[0]])
print type(apple_df[['Date']])
print type(apple_df[['Date', 'Close']])
print type(apple_df['Date'])

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [309]:
print apple_df.Date
print apple_df.Close

0     30-Sep-16
1     29-Sep-16
2     28-Sep-16
3     27-Sep-16
4     26-Sep-16
5     23-Sep-16
6     22-Sep-16
7     21-Sep-16
8     20-Sep-16
9     19-Sep-16
10    16-Sep-16
11    15-Sep-16
12    14-Sep-16
13    13-Sep-16
14    12-Sep-16
15     9-Sep-16
16     8-Sep-16
17     7-Sep-16
18     6-Sep-16
19     2-Sep-16
20     1-Sep-16
Name: Date, dtype: object
0     113.05
1     112.18
2     113.95
3     113.09
4     112.88
5     112.71
6     114.62
7     113.55
8     113.57
9     113.58
10    114.92
11    115.57
12    111.77
13    107.95
14    105.44
15    103.13
16    105.52
17    108.36
18    107.70
19    107.73
20    106.73
Name: Close, dtype: float64


* row 선택하기
  - Seires의 경우 []로 row 선택이 가능하나, DataFrame의 경우는 기본적으로 column을 선택하도록 설계
  - [:10]과 같이 slicing의 경우에는 row 선택 가능
  - .loc(index), .iloc(0base,index), .ix(둘다) 의 함수로 row 선택 가능
  

In [310]:
print apple_df[:10]

        Date    Open    High     Low   Close    Volume
0  30-Sep-16  112.46  113.37  111.80  113.05  36379106
1  29-Sep-16  113.16  113.80  111.80  112.18  35886990
2  28-Sep-16  113.69  114.64  113.43  113.95  29641085
3  27-Sep-16  113.00  113.18  112.34  113.09  24607412
4  26-Sep-16  111.64  113.39  111.55  112.88  29869442
5  23-Sep-16  114.42  114.79  111.55  112.71  52481151
6  22-Sep-16  114.35  114.94  114.00  114.62  31073984
7  21-Sep-16  113.85  113.99  112.44  113.55  36003185
8  20-Sep-16  113.05  114.12  112.51  113.57  34514269
9  19-Sep-16  115.19  116.18  113.25  113.58  47023046


In [311]:
sample_df = pd.read_csv('sample.csv', index_col = 'Symbol', usecols = [0, 1, 2, 3, 7])
print sample_df['MMM' : 'ACN']

                       Name                  Sector   Price  Book Value
Symbol                                                                 
MMM              3M Company             Industrials  177.12       19.34
ABT     Abbott Laboratories             Health Care   41.89       14.10
ABBV                 AbbVie             Health Care   64.16        2.87
ACN           Accenture plc  Information Technology  115.11       11.45


In [312]:
print sample_df.loc['MMM']

Name           3M Company
Sector        Industrials
Price              177.12
Book Value          19.34
Name: MMM, dtype: object


In [313]:
print sample_df.loc[['MMM', 'MSFT']]

                   Name                  Sector   Price  Book Value
Symbol                                                             
MMM          3M Company             Industrials  177.12       19.34
MSFT    Microsoft Corp.  Information Technology   52.30        9.51


In [314]:
print sample_df.iloc[[0, 1, 2]]
print type(sample_df.iloc[[0, 1, 2]])

print sample_df.iloc[0] 
print type(sample_df.iloc[0])

                       Name       Sector   Price  Book Value
Symbol                                                      
MMM              3M Company  Industrials  177.12       19.34
ABT     Abbott Laboratories  Health Care   41.89       14.10
ABBV                 AbbVie  Health Care   64.16        2.87
<class 'pandas.core.frame.DataFrame'>
Name           3M Company
Sector        Industrials
Price              177.12
Book Value          19.34
Name: MMM, dtype: object
<class 'pandas.core.series.Series'>


In [105]:
print sample_df.ix[['MSFT', 'ZTS']]

                   Name                  Sector  Price  Book Value
Symbol                                                            
MSFT    Microsoft Corp.  Information Technology   52.3        9.51
ZTS              Zoetis             Health Care   48.5        2.35


In [106]:
print sample_df.ix[[10, 11, 12, 15]]

                                 Name       Sector   Price  Book Value
Symbol                                                                
AMG     Affiliated Managers Group Inc   Financials  138.85       53.30
AFL                         AFLAC Inc   Financials   72.49       48.22
A            Agilent Technologies Inc  Health Care   45.48       12.79
ALK              Alaska Air Group Inc  Industrials   59.86       19.81


* boolean selection으로 row 선택하기

In [315]:
print sample_df.Price > 100

Symbol
MMM       True
ABT      False
ABBV     False
ACN       True
ATVI     False
AYI       True
ADBE     False
AAP       True
AES      False
AET       True
AMG       True
AFL      False
A        False
APD       True
AKAM     False
ALK      False
ALB      False
AA       False
ALXN      True
ALLE     False
AGN       True
ADS       True
LNT      False
ALL      False
GOOGL     True
GOOG      True
MO       False
AMZN      True
AEE      False
AAL      False
         ...  
V        False
VNO       True
VMC       True
WMT      False
WBA      False
WM       False
WAT       True
WFC      False
HCN      False
WDC      False
WU       False
WRK      False
WY       False
WHR       True
WFM      False
WMB      False
WLTW      True
WEC      False
WYN      False
WYNN     False
XEL      False
XRX      False
XLNX     False
XL       False
XYL      False
YHOO     False
YUM      False
ZBH       True
ZION     False
ZTS      False
Name: Price, dtype: bool


In [317]:
print sample_df[sample_df.Price > 100][['Price']]
# 결과값이 데이타프레임이기 때문에 뒤에 [['column']]으로 원하는 것만 추출 가능

         Price
Symbol        
MMM     177.12
ACN     115.11
AYI     264.62
AAP     164.85
AET     117.00
AMG     138.85
APD     144.35
ALXN    124.42
AGN     240.59
ADS     200.96
GOOGL   717.78
GOOG    705.63
AMZN    745.81
AMT     113.66
AMGN    161.10
ANTM    132.15
AON     109.57
AZO     815.02
AVGO    155.14
AVB     184.94
BCR     239.00
BDX     175.64
BRK-B   143.65
BIIB    251.30
BLK     345.20
BA      130.09
BXP     133.32
CELG    105.03
CVX     104.77
CMG     399.71
...        ...
RTN     138.49
REGN    378.35
ROK     115.70
ROP     170.04
SPGI    108.87
SRE     114.11
SHW     306.52
SPG     219.56
SLG     105.98
SJM     154.08
SNA     160.16
SWK     114.97
SRCL    104.70
SYK     122.29
CLX     138.37
HSY     110.70
TRV     118.08
TMO     152.69
TDG     269.81
ULTA    250.82
UNH     141.27
UPS     109.52
UTX     103.66
UHS     137.16
VNO     100.46
VMC     123.61
WAT     146.53
WHR     171.38
WLTW    125.06
ZBH     124.89

[122 rows x 1 columns]


* 새 column 추가하기

In [318]:
# 굉장히 많이 쓰인다.
copy = sample_df.copy()
copy['TwicePrice'] = sample_df.Price * 2
print copy[:10]

                       Name                  Sector   Price  Book Value  \
Symbol                                                                    
MMM              3M Company             Industrials  177.12       19.34   
ABT     Abbott Laboratories             Health Care   41.89       14.10   
ABBV                 AbbVie             Health Care   64.16        2.87   
ACN           Accenture plc  Information Technology  115.11       11.45   
ATVI    Activision Blizzard  Information Technology   41.29       11.31   
AYI       Acuity Brands Inc             Industrials  264.62       36.50   
ADBE      Adobe Systems Inc  Information Technology   96.79       14.53   
AAP      Advance Auto Parts  Consumer Discretionary  164.85       35.82   
AES                AES Corp               Utilities   12.32        4.86   
AET               Aetna Inc             Health Care  117.00       47.96   

        TwicePrice  
Symbol              
MMM         354.24  
ABT          83.78  
ABBV        128

In [319]:
copy.insert(1, 'TriplePrice', sample_df.Price * 3) # insert ( 몇번째 column, 조건)
print copy[:2]

                       Name  TriplePrice       Sector   Price  Book Value  \
Symbol                                                                      
MMM              3M Company       531.36  Industrials  177.12       19.34   
ABT     Abbott Laboratories       125.67  Health Care   41.89       14.10   

        TwicePrice  
Symbol              
MMM         354.24  
ABT          83.78  


 * column 삭제하기

In [124]:
print copy[:2]
del copy['Sector']
print copy[:2]

                       Name  TriplePrice       Sector   Price  Book Value  \
Symbol                                                                      
MMM              3M Company       531.36  Industrials  177.12       19.34   
ABT     Abbott Laboratories       125.67  Health Care   41.89       14.10   

        TwicePrice  
Symbol              
MMM         354.24  
ABT          83.78  
                       Name  TriplePrice   Price  Book Value  TwicePrice
Symbol                                                                  
MMM              3M Company       531.36  177.12       19.34      354.24
ABT     Abbott Laboratories       125.67   41.89       14.10       83.78


 * row 추가/삭제하기

In [129]:
df1 = copy.iloc[0:3].copy()
copy = copy.append(df1)
copy.tail() # head와 tail이 print기능이 포함되어 있다.

copy.loc['Aaron'] = ['Aaron', 1000.0, 1000.0, 1000.0, 2000.0] # 이런식으론 잘 안쓴다.
copy.tail()

Name  TriplePrice    Price  Book Value  TwicePrice
Symbol                                                                   
ABBV                 AbbVie       192.48    64.16        2.87      128.32
MMM              3M Company       531.36   177.12       19.34      354.24
ABT     Abbott Laboratories       125.67    41.89       14.10       83.78
ABBV                 AbbVie       192.48    64.16        2.87      128.32
Aaron                 Aaron      1000.00  1000.00     1000.00     2000.00

In [137]:
copy = copy.drop(['Aaron'])
copy.tail()

Name  TriplePrice   Price  Book Value  TwicePrice
Symbol                                                                  
ABT     Abbott Laboratories       125.67   41.89       14.10       83.78
ABBV                 AbbVie       192.48   64.16        2.87      128.32
MMM              3M Company       531.36  177.12       19.34      354.24
ABT     Abbott Laboratories       125.67   41.89       14.10       83.78
ABBV                 AbbVie       192.48   64.16        2.87      128.32

In [320]:
selection = sample_df.Price > 200
lessthan200 = sample_df[-selection] # boolin selection에서 -가 붙으면 반전이다.
print lessthan200[:2]

morethan200 = sample_df[selection]
print morethan200[:3]

                       Name       Sector   Price  Book Value
Symbol                                                      
MMM              3M Company  Industrials  177.12       19.34
ABT     Abbott Laboratories  Health Care   41.89       14.10
                         Name                  Sector   Price  Book Value
Symbol                                                                   
AYI         Acuity Brands Inc             Industrials  264.62       36.50
AGN              Allergan plc             Health Care  240.59      183.41
ADS     Alliance Data Systems  Information Technology  200.96       29.51
